# Generated by Django 5.1.4 on 2024-12-24 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TodoItem",
            new_name="Task",
        ),
    ]
